### ISSUE TITLE
ram example fails to build

### ISSUE THREAD

**Issue by HendrikKlug-synthara** [antmicro/renode-verilator-integration#4]
Hi, I'm trying to run the renode-verilator-integration [ram example](https://github.com/antmicro/renode-verilator-integration/tree/master/samples/ram) but I'm not able to compile it.

These are the steps I'm following:
```bash 
mkdir renode_portable
wget https://builds.renode.io/renode-latest.linux-portable.tar.gz
tar xf  renode-latest.linux-portable.tar.gz -C renode_portable --strip-components=1

git clone https://github.com/antmicro/renode-verilator-integration.git

cd renode-verilator-integration/samples/ram
mkdir build
cd build
cmake .. -DUSER_RENODE_DIR=/tmp/tmp.1uQFcXQofk/renode_portable -GNinja
ninja
```

I'm getting the error `/tmp/tmp.1uQFcXQofk/renode_portable/plugins/IntegrationLibrary/src/renode_bus.h:11:10: fatal error: ../../../../Infrastructure/src/Emulator/Cores/renode/include/renode_imports.h: No such file or directory`

This is the full output of the ninja command: 
[ninja_out.txt](https://github.com/user-attachments/files/17733781/ninja_out.txt)

I can't find the file "renode_imports.h" anywhere in the tree.
I also couldn't find out where the macro `EXTERNAL_AS` could be defined somewhere else.

**Comment by JanOlencki** [comment]
Hi Hendrik

Unfortunately the portable version of Renode isn't enough to build example from the repository. You need to clone the Renode repository as described in [our documentation](https://renode.readthedocs.io/en/latest/tutorials/co-simulating-custom-hdl.html#building-a-verilated-peripheral). You don't need to build Renode from source, just make source available for CMake.
It's worth mention that our [integration over DPI](https://github.com/antmicro/renode-dpi-examples) doesn't require cloning the Renode repository.

**Comment by HendrikKlug-synthara** [comment]
Hi Jan, right, it worked with the cloned Renode repository. Thanks for your help!
